import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "About Edge Metric Sports - a free, data-driven NFL prediction site.",
};

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-8 sm:px-6">
      <h1 className="mb-4 text-4xl font-black tracking-tight">About</h1>
      <div className="space-y-4 text-sm leading-relaxed text-muted">
        <p>
          Edge Metric Sports is a free, ad-supported NFL prediction site built on top of a reproducible, testable
          quantitative pipeline - not gut feel, not a paid tipster service, and not a subscription product.
        </p>
        <p>
          Every number you see - a projected score, a win probability, a market line - is generated by versioned
          statistical models and stored exactly as produced. Nothing is adjusted after the fact to look better in
          hindsight.
        </p>
        <p>
          We publish picks only when our full pipeline - model, market, and research - agrees there&apos;s a real
          edge, and we track every one of them, win or lose, in an immutable public record.
        </p>
        <p>
          See <a href="/methodology" className="font-semibold text-accent hover:underline">Methodology</a> for how
          the system actually works, and <a href="/nfl/performance" className="font-semibold text-accent hover:underline">Performance</a> for
          the verified results.
        </p>
      </div>
    </div>
  );
}
