import Link from "next/link";

export default function SiteFooter() {
  return (
    <footer className="mt-16 border-t border-border bg-surface">
      <div className="mx-auto max-w-6xl px-4 py-8 text-sm text-muted sm:px-6">
        <p className="mb-3">
          Predictions are generated by a quantitative model and are for informational purposes only.
          Nothing on this site is financial advice. Please gamble responsibly.
        </p>
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex flex-wrap gap-4">
            <Link href="/methodology" className="hover:text-foreground">Methodology</Link>
            <Link href="/about" className="hover:text-foreground">About</Link>
            <Link href="/nfl/performance" className="hover:text-foreground">Verified Record</Link>
          </div>
          <p className="text-xs text-muted">&copy; {new Date().getFullYear()} Edge Metric Sports</p>
        </div>
      </div>
    </footer>
  );
}
